### ISSUE TITLE
What advantage does this have over the underlying library?

### ISSUE THREAD

**Issue by miketheman** [sdogruyol/kemal-redis#1]
Hi there!

When looking at this library, I don't think I understand what it provides over the underlying library - can you please elaborate?

Especially if I want to use kemal-redis, and the underlying lib had progressed beyond 1.2.1, so there ought to be some version relaxing there.

Thanks!

**Comment by sdogruyol** [comment]
Actually, not much! I've just made these helpers to easily integrate redis as a middleware

**Comment by miketheman** [comment]
Thanks - I don't know if I truly understand the differentiation - and I've opened up PR #2 to relax the dependency constraints.
